### PR TITLE
Feature/extract plotly

### PR DESCRIPTION
**Pull request by grallewellyn**
Removed `npm install jupyterlab-plotly@5.5.0` because that is now being installed in the environment.yml. To successfully do this, you need to also remove `jlpm cache clean` and we don't need this command anymore since `jupyter lab clean` covers it now

### CODE REVIEW

**Comment by anilnatha** [comment]
@grallewellyn I'm not seeing the installation of `jupyterlab-plotly` in our `environment.yml` in this PR, was that done in a different set of changes?

**Comment by grallewellyn** [comment]
@anilnatha `plotly` is already in our environment.yml and is being upgraded in the `feature/update-packages` PR 
`plotly` is the conda distribution of the same package, both pages (https://www.npmjs.com/package/jupyterlab-plotly and https://anaconda.org/conda-forge/plotly) list this repo: https://github.com/plotly/plotly.py as their source

**Comment by anilnatha** [comment]
@grallewellyn Interesting, I didn't know those were the same package. Thanks for the insight.

**Review by anilnatha — APPROVED** [review]
LGTM!

**Pull request merged**
