### PR TITLE
Feature/remove collaboration

### PR DESCRIPTION
**Pull request by grallewellyn**
Removed the collaboration tag from launching jupyter notebook because it was causing blank notebook errors and jumping errors within the cells 
Tested this successfully 5 times with 5 notebooks in R and and 5 times with 5 notebooks in vanilla, following these steps:
1. Create a new notebook and add some content. Make sure no jumping error
2. Save notebook
3. Stop and restart workspace
4. Open notebook back up and make sure it isn't just a blank screen 

Also tested this successfully in jupyterlab 3.6.4 5 times with 5 notebooks in R and and 5 times with 5 notebooks in vanilla, but I think we should avoid bumping the jupyterlab version if possible 

People should test this if they can to confirm the errors have gone away 

Pipeline created here with all successful image builds: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/2876

Can test in DIT using the branch name `remove-collaboration`. I confirmed all 6 base images build successfully in DIT

### CODE REVIEW

**Review by gchang — APPROVED** [review]
Looks good, please add a ticket with a link to relevant Jupyterlab issue to remind us to keep tabs on how they resolve it upstream.

**Comment by grallewellyn** [comment]
Relevant issues:
https://github.com/jupyterlab/jupyterlab/issues/14278
https://github.com/jupyterlab/jupyterlab/issues/13930#issuecomment-1424247367 (but this one is supposed to be resolved)

**Comment by rtapella** [comment]
fixes https://github.com/MAAP-Project/Community/issues/735

**Comment by rtapella** [comment]
might also fix: https://github.com/orgs/MAAP-Project/discussions/784

**Pull request merged**
