### PR TITLE
Features/optimize jlab images addresses

### PR DESCRIPTION
**Pull request by sujen1412**
This relates to https://github.com/MAAP-Project/Community/issues/970

### CODE REVIEW

**Review by anilnatha — COMMENTED** [review]
In reviewing the code last week, these changes look good, but also need to verify that all images do build successfully.

**Comment by sujen1412** [comment]
All images built except isce2, are we not getting rid of that image? 
https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/4060

**Comment by anilnatha** [comment]
We discussed "freezing" that one during the last release and need to discuss when we will retire it.

CC: @grallewellyn

**Comment by grallewellyn** [comment]
libmamba caused isce2 to start breaking so maybe freeze before that merge

**Comment by anilnatha** [comment]
@sujen1412 I'm closing this pull request. We will revisit additional optimizations needed at a future time as we've already integrated the optimizations shown in this PR to the best of my knowledge.

**Pull request closed without merging**
