### PR TITLE
Feature/libmamba solver

### PR DESCRIPTION
**Pull request by grallewellyn**
- no longer using mamba
- now using conda with libmamba solver 
- updated versions of base_images/vanilla packages to be consistent with higher level package versions that base_images/pangeo was using because I was getting dependency errors 
- isce2 and rgedi going to be removed, but edited them anyway to be consistent 
- all base_images starting out with 
```
RUN conda install -y -c conda-forge pyOpenSSL=23.2.0 && \
    conda install -y -n base conda-libmamba-solver && \
    conda config --set solver libmamba
```
to be consistent across 
Note that `conda install -y -c conda-forge pyOpenSSL=23.2.0` fixed a building bug for 3 of the images earlier 
- believed to solve/ reduce `ImportError: libarchive.so.13: cannot open shared object file: No such file or directory` when building images
- Added
```
ENV LANG en_US.UTF-8
ENV TZ US/Pacific
ARG DEBIAN_FRONTEND=noninteractive
``` 
to the beginning of base_images/vanilla to be consistent 
- built both `develop` and `feature/libmamba-solver` branches and times were
vanilla: 14 minutes 11 seconds (libmamba) vs 23 minutes and 18 seconds (develop)
isce3: 25 minutes 17 seconds (libmamba) vs 14 minutes 6 seconds (develop)
r: 16 minutes 53 seconds (libmamba) vs 24 minutes and 52 seconds (develop)
pangeo: 14 minutes 53 seconds (libmamba) vs 15 minutes 49 seconds (develop)

- Find successful build of 4 relevant images here: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/3650 
Note that isce2 is failing to build with dependency issues, but in the 9/20 hackathon we decided it wasn't worth trying to fix 
I got rGEDI to work one time here: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/3669, but then it kept failing later so I just removed [the fix](https://github.com/MAAP-Project/maap-workspaces/commit/f9ee723f135f486ca62c9f28a82722f260ad8a68)
I can keep working on fixing rGEDI, but I didn't think it was worth the time since we decided to get rid of it 
Find build of develop here for comparisons: https://repo.dit.maap-project.org/root/maap-workspaces/-/pipelines/3659 

@anilnatha noticed that libmamba solver is ignoring the nodefaults channel tag in the .yml file and it is a bug others have noticed. In the hackathon we decided to just let it be for now and libmamba solver will become even faster once this bug is fixed 

Also, Alex mentioned we should freeze isce2 and rgedi on a working image and this PR fails for both those images so maybe we freeze those images before merging this PR? Again, I tried briefly to get isce2 and rgedi working but wasn't sure it was worth the time 

Updating documentation to tell users to use `conda install` instead of `mamba install`

### CODE REVIEW

**Review by anilnatha — COMMENTED** [review]
Since we've set libmamba as the default solver, the conda install option `--solver=libmamba` isn't needed, but I like that you explicitly added the option to be clear/certain that the installation is using the libmamba solver.

**Review by anilnatha — APPROVED** [review]
LGTM!

**Comment by grallewellyn** [comment]
Thanks @anilnatha! What do you think about freezing isce2 and rgedi on the current working develop image? This PR fails for both those images so maybe we freeze those images before merging this PR? Again, I tried briefly to get isce2 and rgedi working but wasn't sure it was worth the time

**Comment by anilnatha** [comment]
> Thanks @anilnatha! What do you think about freezing isce2 and rgedi on the current working develop image? This PR fails for both those images so maybe we freeze those images before merging this PR? Again, I tried briefly to get isce2 and rgedi working but wasn't sure it was worth the time

If I'm understanding correctly, you're proposing that we use the current images for rgedi and isce2 for the next release since we know they will fail the build process with these changes? if so, I think this is sound. We probably should to discuss retiring these if very few are using them, or nobody is using them for that matter. @grallewellyn

**Comment by grallewellyn** [comment]
@anilnatha Sujen asked if anyone was using rgedi and there was one reply: https://github.com/orgs/MAAP-Project/discussions/786
I think freezing them sounds like a good plan so that users can still use them as long as we have a warning that they are no longer supported

**Comment by anilnatha** [comment]
Sounds good to me, I want to learn how we actually go about "freezing" them during our release process.

**Review by sujen1412 — APPROVED** [review]

**Pull request merged**
