### PR TITLE
Add STAC_BROWSER_URL env var

### PR DESCRIPTION
**Pull request by wildintellect**
We missed a currently required ENV variable.

### CODE REVIEW

**Comment by wildintellect** [comment]
@anilnatha give me a few this PR has an error.

**Comment by wildintellect** [comment]
@anilnatha so this will prevent the error, however for the feature to correctly work we need https://github.com/MAAP-Project/stac_ipyleaflet/pull/117 and a new release.

**Comment by anilnatha** [comment]
@wildintellect The env var addition here looks good to me, can I go ahead and merge this PR and handle the 0.3.4 update separately?

**Comment by wildintellect** [comment]
Yes that should be ok, this add will at least prevent the widget from throwing an error.

**Review by anilnatha — APPROVED** [review]
LGTM!

**Pull request merged**
